language: php
php:
    - 7.4

install:
    - travis_retry cd src && composer install --no-progress --prefer-dist

before_script: cd src
script:
    - composer test

after_success:
    - composer require --dev php-coveralls/php-coveralls
    - travis_retry php vendor/bin/php-coveralls --config ./tests/.coveralls.yml

sudo: false

cache:
    directories:
        - $HOME/.composer/cache

notifications:
    email: false
