version: "3.7"
services:
  event_ticketer:
    environment:
      PHP_IDE_CONFIG: "serverName=event_ticketer"
      XDEBUG_MODE: "debug"
      MAIL_TLS: "off"
      MAIL_HOST: "mailhog"
      MAIL_PORT: "1025"
      MAIL_USER: ""
      MAIL_PASS: ""
      MAIL_FROM_ADDRESS: "system@test.foo"
      API_AUTH_TOKENS: '["AeDaipaingeengoiX6aeleaRee5EuphooyohkeeQu7fehudunidaeb0al1aziith"]'
    build:
      target: dev
    image: stopka/event_ticketer:dev
    ports:
      - 80:80
    volumes:
      - ./src:/srv
      - composer-cache:/root/.composer
      - ~/.config/composer/auth.json:/root/.config/auth.json:ro
    networks:
      - mail
  event_ticketer-mariadb:
    ports:
      - 3306:3306

  adminer:
    image: adminer:latest
    ports:
      - 8080:8080
    networks:
      - event_ticketer-mariadb

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - 8025:8025
    networks:
      - mail
volumes:
  composer-cache:
networks:
  mail:
