version: "3.7"
services:
  event_ticketer:
    environment:
      PHP_IDE_CONFIG: "serverName=event_ticketer"
      XDEBUG_MODE: "debug"
      MAIL_HOST: "mailhog"
      MAIL_PORT: "1025"
    build:
      target: dev
    image: stopka/event_ticketer:dev
    ports:
      - 80:80
    volumes:
      - ./src:/srv
      - composer-cache:/root/.composer
      - ~/.config/composer/:/root/.config/composer/:ro
    networks:
      - mail
  event_ticketer-mariadb:
    ports:
      - 3306:3306
  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - 8025:8025
    networks:
      - mail
volumes:
  composer-cache:
networks:
  mail:
