version: "3.7"
services:
  event_ticketer:
    build:
      context: .
      target: prod
    image: stopka/event_ticketer:latest
    networks:
      - event_ticketer-mariadb
    environment:
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
    logging:
      driver: "json-file"
      options:
        max-size: "1M"
        max-file: "10"
  event_ticketer-mariadb:
    image: mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_DATABASE=${DATABASE_NAME}
    volumes:
      - event_ticketer-mariadb-data:/var/lib/mysql
    networks:
      event_ticketer-mariadb:
          aliases:
              - database
    logging:
      driver: "json-file"
      options:
        max-size: "1M"
        max-file: "10"
volumes:
  event_ticketer-mariadb-data:
networks:
  event_ticketer-mariadb:
