<?php

declare(strict_types=1);

namespace Ticketer\Model\Database\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20210110190452 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add initial db schema';
    }

    public function up(Schema $schema): void
    {
        $sql = <<<EOL
CREATE TABLE application_number (id INT AUTO_INCREMENT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB;
CREATE TABLE administrator (id CHAR(22) NOT NULL COMMENT '(DC2Type:uuid)', username VARCHAR(255) NOT NULL, password VARCHAR(255) DEFAULT NULL, first_name VARCHAR(255) DEFAULT NULL, last_name VARCHAR(255) DEFAULT NULL, email VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB;
CREATE TABLE reservation (id CHAR(22) NOT NULL COMMENT '(DC2Type:uuid)', event_id CHAR(22) DEFAULT NULL COMMENT '(DC2Type:uuid)', number_id INT DEFAULT NULL, state SMALLINT NOT NULL, first_name VARCHAR(255) DEFAULT NULL, last_name VARCHAR(255) DEFAULT NULL, email VARCHAR(255) DEFAULT NULL, created DATETIME DEFAULT NULL COMMENT '(DC2Type:datetime_immutable)', INDEX IDX_42C8495571F7E88B (event_id), UNIQUE INDEX UNIQ_42C8495530A1DE10 (number_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB;
CREATE TABLE price_amount (id CHAR(22) NOT NULL COMMENT '(DC2Type:uuid)', price_id CHAR(22) DEFAULT NULL COMMENT '(DC2Type:uuid)', currency_id CHAR(22) DEFAULT NULL COMMENT '(DC2Type:uuid)', amount DOUBLE PRECISION NOT NULL, INDEX IDX_C338D812D614C7E7 (price_id), INDEX IDX_C338D81238248176 (currency_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB;
CREATE TABLE early (id CHAR(22) NOT NULL COMMENT '(DC2Type:uuid)', early_wave_id CHAR(22) DEFAULT NULL COMMENT '(DC2Type:uuid)', first_name VARCHAR(255) DEFAULT NULL, last_name VARCHAR(255) DEFAULT NULL, email VARCHAR(255) DEFAULT NULL, INDEX IDX_A38ECE4B1BC1A8A6 (early_wave_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB;
CREATE TABLE choice (id CHAR(22) NOT NULL COMMENT '(DC2Type:uuid)', application_id CHAR(22) DEFAULT NULL COMMENT '(DC2Type:uuid)', option_id CHAR(22) DEFAULT NULL COMMENT '(DC2Type:uuid)', payed TINYINT(1) NOT NULL, INDEX IDX_C1AB5A923E030ACD (application_id), INDEX IDX_C1AB5A92A7C41D6F (option_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB;
CREATE TABLE price (id CHAR(22) NOT NULL COMMENT '(DC2Type:uuid)', PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB;
CREATE TABLE insurance_company (id CHAR(22) NOT NULL COMMENT '(DC2Type:uuid)', code VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB;
CREATE TABLE event (id CHAR(22) NOT NULL COMMENT '(DC2Type:uuid)', state SMALLINT NOT NULL, name VARCHAR(255) NOT NULL, start_date DATETIME DEFAULT NULL COMMENT '(DC2Type:datetime_immutable)', internal_info LONGTEXT DEFAULT NULL, occupancy_icon VARCHAR(255) DEFAULT NULL, capacity INT DEFAULT NULL, capacity_full TINYINT(1) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB;
CREATE TABLE substitute (id CHAR(22) NOT NULL COMMENT '(DC2Type:uuid)', number_id INT DEFAULT NULL, event_id CHAR(22) DEFAULT NULL COMMENT '(DC2Type:uuid)', early_id CHAR(22) DEFAULT NULL COMMENT '(DC2Type:uuid)', state SMALLINT NOT NULL, count INT NOT NULL, first_name VARCHAR(255) DEFAULT NULL, last_name VARCHAR(255) DEFAULT NULL, email VARCHAR(255) DEFAULT NULL, end_date DATETIME DEFAULT NULL COMMENT '(DC2Type:datetime_immutable)', created DATETIME DEFAULT NULL COMMENT '(DC2Type:datetime_immutable)', UNIQUE INDEX UNIQ_CFF353B930A1DE10 (number_id), INDEX IDX_CFF353B971F7E88B (event_id), INDEX IDX_CFF353B945F7F355 (early_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB;
CREATE TABLE early_wave (id CHAR(22) NOT NULL COMMENT '(DC2Type:uuid)', event_id CHAR(22) DEFAULT NULL COMMENT '(DC2Type:uuid)', invite_sent TINYINT(1) NOT NULL, start_date DATETIME DEFAULT NULL COMMENT '(DC2Type:datetime_immutable)', name VARCHAR(255) NOT NULL, INDEX IDX_5011F45F71F7E88B (event_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB;
CREATE TABLE currency (id CHAR(22) NOT NULL COMMENT '(DC2Type:uuid)', symbol VARCHAR(255) NOT NULL, code VARCHAR(255) NOT NULL, `default` TINYINT(1) NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB;
CREATE TABLE cart_number (id INT AUTO_INCREMENT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB;
CREATE TABLE `option` (id CHAR(22) NOT NULL COMMENT '(DC2Type:uuid)', addition_id CHAR(22) DEFAULT NULL COMMENT '(DC2Type:uuid)', price_id CHAR(22) DEFAULT NULL COMMENT '(DC2Type:uuid)', description LONGTEXT DEFAULT NULL, auto_select SMALLINT NOT NULL, position INT NOT NULL, name VARCHAR(255) NOT NULL, capacity INT DEFAULT NULL, capacity_full TINYINT(1) NOT NULL, internal_info LONGTEXT DEFAULT NULL, occupancy_icon VARCHAR(255) DEFAULT NULL, INDEX IDX_5A8600B082BDE102 (addition_id), INDEX IDX_5A8600B0D614C7E7 (price_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB;
CREATE TABLE reservation_number (id INT AUTO_INCREMENT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB;
CREATE TABLE application (id CHAR(22) NOT NULL COMMENT '(DC2Type:uuid)', number_id INT DEFAULT NULL, cart_id CHAR(22) DEFAULT NULL COMMENT '(DC2Type:uuid)', event_id CHAR(22) DEFAULT NULL COMMENT '(DC2Type:uuid)', reservation_id CHAR(22) DEFAULT NULL COMMENT '(DC2Type:uuid)', insurance_company_id CHAR(22) DEFAULT NULL COMMENT '(DC2Type:uuid)', state SMALLINT NOT NULL, friend LONGTEXT DEFAULT NULL, info LONGTEXT DEFAULT NULL, first_name VARCHAR(255) DEFAULT NULL, last_name VARCHAR(255) DEFAULT NULL, gender SMALLINT DEFAULT NULL, address VARCHAR(255) DEFAULT NULL, city VARCHAR(255) DEFAULT NULL, zip VARCHAR(255) DEFAULT NULL, country VARCHAR(255) DEFAULT NULL, birth_date DATE DEFAULT NULL, created DATETIME DEFAULT NULL COMMENT '(DC2Type:datetime_immutable)', UNIQUE INDEX UNIQ_A45BDDC130A1DE10 (number_id), INDEX IDX_A45BDDC11AD5CDBF (cart_id), INDEX IDX_A45BDDC171F7E88B (event_id), INDEX IDX_A45BDDC1B83297E7 (reservation_id), INDEX IDX_A45BDDC1ECB24509 (insurance_company_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB;
CREATE TABLE addition (id CHAR(22) NOT NULL COMMENT '(DC2Type:uuid)', visibility_id CHAR(22) DEFAULT NULL COMMENT '(DC2Type:uuid)', event_id CHAR(22) DEFAULT NULL COMMENT '(DC2Type:uuid)', required_for_state SMALLINT DEFAULT NULL, enough_for_state SMALLINT DEFAULT NULL, minimum INT NOT NULL, maximum INT NOT NULL, position INT NOT NULL, name VARCHAR(255) NOT NULL, UNIQUE INDEX UNIQ_EAE9B399B7157780 (visibility_id), INDEX IDX_EAE9B39971F7E88B (event_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB;
CREATE TABLE substitute_number (id INT AUTO_INCREMENT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB;
CREATE TABLE addition_visibility (id CHAR(22) NOT NULL COMMENT '(DC2Type:uuid)', reservation TINYINT(1) NOT NULL, registration TINYINT(1) NOT NULL, customer TINYINT(1) NOT NULL, preview TINYINT(1) NOT NULL, export TINYINT(1) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB;
CREATE TABLE cart (id CHAR(22) NOT NULL COMMENT '(DC2Type:uuid)', number_id INT DEFAULT NULL, event_id CHAR(22) DEFAULT NULL COMMENT '(DC2Type:uuid)', early_id CHAR(22) DEFAULT NULL COMMENT '(DC2Type:uuid)', substitute_id CHAR(22) DEFAULT NULL COMMENT '(DC2Type:uuid)', state INT NOT NULL, first_name VARCHAR(255) DEFAULT NULL, last_name VARCHAR(255) DEFAULT NULL, email VARCHAR(255) DEFAULT NULL, phone VARCHAR(255) DEFAULT NULL, created DATETIME DEFAULT NULL COMMENT '(DC2Type:datetime_immutable)', UNIQUE INDEX UNIQ_BA388B730A1DE10 (number_id), INDEX IDX_BA388B771F7E88B (event_id), INDEX IDX_BA388B745F7F355 (early_id), UNIQUE INDEX UNIQ_BA388B719ECAD51 (substitute_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB;
ALTER TABLE reservation ADD CONSTRAINT FK_42C8495571F7E88B FOREIGN KEY (event_id) REFERENCES event (id);
ALTER TABLE reservation ADD CONSTRAINT FK_42C8495530A1DE10 FOREIGN KEY (number_id) REFERENCES reservation_number (id);
ALTER TABLE price_amount ADD CONSTRAINT FK_C338D812D614C7E7 FOREIGN KEY (price_id) REFERENCES price (id);
ALTER TABLE price_amount ADD CONSTRAINT FK_C338D81238248176 FOREIGN KEY (currency_id) REFERENCES currency (id);
ALTER TABLE early ADD CONSTRAINT FK_A38ECE4B1BC1A8A6 FOREIGN KEY (early_wave_id) REFERENCES early_wave (id);
ALTER TABLE choice ADD CONSTRAINT FK_C1AB5A923E030ACD FOREIGN KEY (application_id) REFERENCES application (id);
ALTER TABLE choice ADD CONSTRAINT FK_C1AB5A92A7C41D6F FOREIGN KEY (option_id) REFERENCES `option` (id);
ALTER TABLE substitute ADD CONSTRAINT FK_CFF353B930A1DE10 FOREIGN KEY (number_id) REFERENCES substitute_number (id);
ALTER TABLE substitute ADD CONSTRAINT FK_CFF353B971F7E88B FOREIGN KEY (event_id) REFERENCES event (id);
ALTER TABLE substitute ADD CONSTRAINT FK_CFF353B945F7F355 FOREIGN KEY (early_id) REFERENCES early (id);
ALTER TABLE early_wave ADD CONSTRAINT FK_5011F45F71F7E88B FOREIGN KEY (event_id) REFERENCES event (id);
ALTER TABLE `option` ADD CONSTRAINT FK_5A8600B082BDE102 FOREIGN KEY (addition_id) REFERENCES addition (id);
ALTER TABLE `option` ADD CONSTRAINT FK_5A8600B0D614C7E7 FOREIGN KEY (price_id) REFERENCES price (id);
ALTER TABLE application ADD CONSTRAINT FK_A45BDDC130A1DE10 FOREIGN KEY (number_id) REFERENCES application_number (id);
ALTER TABLE application ADD CONSTRAINT FK_A45BDDC11AD5CDBF FOREIGN KEY (cart_id) REFERENCES cart (id);
ALTER TABLE application ADD CONSTRAINT FK_A45BDDC171F7E88B FOREIGN KEY (event_id) REFERENCES event (id);
ALTER TABLE application ADD CONSTRAINT FK_A45BDDC1B83297E7 FOREIGN KEY (reservation_id) REFERENCES reservation (id);
ALTER TABLE application ADD CONSTRAINT FK_A45BDDC1ECB24509 FOREIGN KEY (insurance_company_id) REFERENCES insurance_company (id);
ALTER TABLE addition ADD CONSTRAINT FK_EAE9B399B7157780 FOREIGN KEY (visibility_id) REFERENCES addition_visibility (id);
ALTER TABLE addition ADD CONSTRAINT FK_EAE9B39971F7E88B FOREIGN KEY (event_id) REFERENCES event (id);
ALTER TABLE cart ADD CONSTRAINT FK_BA388B730A1DE10 FOREIGN KEY (number_id) REFERENCES cart_number (id);
ALTER TABLE cart ADD CONSTRAINT FK_BA388B771F7E88B FOREIGN KEY (event_id) REFERENCES event (id);
ALTER TABLE cart ADD CONSTRAINT FK_BA388B745F7F355 FOREIGN KEY (early_id) REFERENCES early (id);
ALTER TABLE cart ADD CONSTRAINT FK_BA388B719ECAD51 FOREIGN KEY (substitute_id) REFERENCES substitute (id);
EOL;
        $this->addSql($sql);
    }

    public function down(Schema $schema): void
    {
        $sql = <<<EOL
DROP TABLE application_number;
DROP TABLE administrator;
DROP TABLE reservation;
DROP TABLE price_amount;
DROP TABLE early;
DROP TABLE choice;
DROP TABLE price;
DROP TABLE insurance_company;
DROP TABLE event;
DROP TABLE substitute;
DROP TABLE early_wave;
DROP TABLE currency;
DROP TABLE cart_number;
DROP TABLE `option`;
DROP TABLE reservation_number;
DROP TABLE application;
DROP TABLE addition;
DROP TABLE substitute_number;
DROP TABLE addition_visibility;
DROP TABLE cart;
EOL;
        $this->addSql($sql);
    }
}
